name: chofer
description: A taxi app for Colima Colima.

version: 1.0.3+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.6         #Requires Android and iOS configuration and Firebase (Just dowload the json files)
  firebase_auth: ^0.15.5+3         #Requires Android configuration and firebase
  google_maps_flutter: ^0.5.26+3   #Requires Android and iOS configuration (iOS: io.flutter.embedded_views_preview YES)
  rxdart: any                      #Doesn't require configuration
  location: ^3.0.2                 #Requires Android configuration
  google_maps_webservice: ^0.0.17  #Doesn't require configuration
  geolocator: ^5.3.2+2             #Requires Android and iOS configuration
  http: ^0.12.1                    #Doesn't require configuration
  provider: ^3.0.0+1               #Doesn't require configuration
  search_map_place: ^0.3.0         #Doesn't require configuration
  path_provider: ^1.6.10           #Doesn't require configuration
  pin_code_fields: ^3.0.1          #Doesn't require configuration
  uuid: 2.1.0                      #Doesn't require configuration
  image_picker: ^0.6.7+2           #Requires iOS configuration 
  assets_audio_player: ^1.3.0      #Doesn't require configuration
  firebase_storage: ^3.1.6         #Doesn't require configuration
  toast: ^0.1.5                    #Doesn't require configuration
  url_launcher: ^5.7.10            #Doesn't require configuration
  cupertino_icons: ^0.1.2          #Doesn't require configuration

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/msg.png
   - assets/location.png
   - assets/empty.png
   - assets/car.png
   - assets/login.png
   - assets/pending.png
   - assets/icon.png
   - assets/tone.mp3
